training:
  batch_size: !!int 32
  seed: !!int 71298
  patience: 15
  epsilon: !!float 1e-6
  random_state: 42
  epochs: 200
  lr: !!float 1e-3
  
data:
  run: 'short_ttm'
  option: 'call' #put, call, or both
  smooth: true
  full_train: false
  window_size: 21
  h_step: !!int 1 #[1, 5, 21]
  covariates: 
  - 'VIX' 
  - 'VVIX' 
  - 'SKEW' 
  - 'RVOL' 
  - 'TMS' 
  - 'CRS'
  - 'EPU' 
  - 'ADS'

model:
  filters: !!int 64 # 16 32 64 128 filter within the conv2DLSTM layer
  kernel_height: !!int 3 # 1 to 9 (moneyness) 3x3 kernel size?
  kernel_width: !!int 4 # 1 to 5 (maturity) mxn -> 9x5
  num_layer: !!int 2 # Any positive integer >0
  strides_dim: !!int 1 # assumes strides to be same across the two dimensions 
  kernel_initializer: 'glorot_uniform'
  recurrent_initializer: 'orthogonal'
  padding: 'same'
  conv_activation: 'tanh'
  recurrent_activation: 'sigmoid'