training:
  window_size: 21
  batch_size: !!int 32
  patience: 15
  epsilon: 0.5
  random_state: 42
  covariates: None

model:
  filters: !!int 2
  kernel_size: [2,3]
  strides: 1
  kernel_initializer: 'glorot_uniform'
  recurrent_initializer: 'orthogonal'
  optimizer: adam
  lr: !!float 1e-3
  lamb: !!float 0.  # regularization parameter

forecast:
  h_step: !!int 1