training:
  batch_size: !!int 32
  seed: !!int 71298
  patience: 15
  epsilon: !!float 1e-6
  random_state: 42
  epochs: 200
  lr: !!float 1e-3
  
data:
  run: 'short_ttm'
  option: 'call' #put, call, or both
  smooth: true
  full_train: false
  window_size: 21
  h_step: !!int 1 #[1, 5, 21]
  covariates: []
  # - 'VIX' 
  # - 'VVIX' 
  # - 'SKEW' 
  # - 'RVOL' 
  # - 'TMS' 
  # - 'CRS'
  # - 'EPU' 
  # - 'ADS'

model:
  num_heads: !!int 4
  key_dim: !!int 16

  note: 'afterfix' # small note to be added in the writing of the results output