training:
  window_size: 21
  batch_size: !!int 32
  patience: 15
  epsilon: !!float 1e-6
  random_state: 42
  epochs: 100
  covariates: None

model:
  run: 'long_ttm'
  filters: !!int 2
  kernel_size: [2,2]
  strides: 1
  kernel_initializer: 'glorot_uniform'
  recurrent_initializer: 'orthogonal'
  optimizer: adam
  lr: !!float 1e-3
  covariates: #[]
    - 'VIX' 
    - 'VVIX' 
    - 'SKEW' 
    - 'RVOL' 
    - 'TMS' 
    - 'CRS'
    - 'EPU' 
    - 'ADS'

forecast:
  h_step: !!int 1